export const SUPABASE_URL = "https://fhybflxdshortjwjejmp.supabase.co";
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoeWJmbHhkc2hvcnRqd2plam1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE5NjQ5MjIsImV4cCI6MjA4NzU0MDkyMn0.PX_PwO2WUQep_KMp8N8sefD_gjifpqekP4AjqebV6Nw";
export const ROOM_CODE = "SALA1";